name: Build and Deploy PHP Composer Projects to S3

on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      #- name: Extract version number
      #  id: get_version
      #  run: |
      #    echo "VERSION=$(php -r 'echo json_decode(file_get_contents("composer.json"))->version;')" >> $GITHUB_ENV
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: us-west-2  # Your AWS region

      - name: Sync to S3 - quick static files
        run: |
          aws s3 cp ./src/public/ s3://calculator.tools/discgolfgame/ --recursive --acl public-read --cache-control max-age=3600