name: Build and Deploy Projects to S3

on:
  push:
    branches:
      - main  # or your default branch
  workflow_dispatch:  # Allows manual triggering

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3

      #- name: Extract version number
      #  id: get_version
      #  run: |
      #    echo "VERSION=$(php -r 'echo json_decode(file_get_contents("composer.json"))->version;')" >> $GITHUB_ENV
      
      - name: Create version.json with commit hash
        run: |
          echo "{\"version\":\"${GITHUB_SHA::12}\"}" > ./src/public/version.json

      - name: Inject version into index.html
        run: |
          sed -i '/<meta name="viewport"/a \    <meta name="app-version" content="'"${GITHUB_SHA::12}"'">' ./src/public/index.html
          sed -i '/<\/head>/i \    <script>window.APP_VERSION = "'"${GITHUB_SHA::12}"'";</script>' ./src/public/index.html

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          aws-region: us-west-2  # Your AWS region

      - name: Sync to S3
        run: |
          aws s3 cp ./src/public/ s3://calculator.tools/discgolfgame/ --recursive --acl public-read --cache-control max-age=3600